version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mariadb:10
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 111111
    ports:
      - "3336:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--skip-character-set-client-handshake"
      - "--lower_case_table_names=0"

  keycloak:
    container_name: keycloak-mysql
    image: quay.io/keycloak/keycloak:20.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 111111
      KC_DB_URL_HOST: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
    ports:
      - "7070:8080"
    command:
      - "start-dev"
    depends_on:
      - mysql
